fix(Rate): 将Rate状态与modelVal解耦
WeBankFinTech/fes-design pull request #662
Opened 2024-03-07 09:10 UTC by Kesonlin

**What kind of change does this PR introduce?** (check at least one)

-   [x] Bugfix
-   [ ] Feature
-   [ ] Code style update
-   [ ] Refactor
-   [ ] Docs
-   [ ] Build-related changes
-   [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

-   [ ] Yes
-   [x ] No

If yes, please describe the impact and migration path for existing applications:

**Related issue (if exists):**
https://github.com/WeBankFinTech/fes-design/issues/642
**Other information:**
由内部状态innerValue去控制Rate星星数

2024-03-08 06:40 UTC, 1zumii requested changes

2024-03-08 07:06 UTC, Kesonlin commented on components/rate/useRate.ts
> +    const innerValue = ref(0)
已修改

2024-03-08 07:31 UTC, 1zumii approved these changes

2024-03-08 08:01 UTC, Kesonlin commented on components/rate/useRate.ts
> -            emit('change', newValue);
确实是，换成useNormalModel后忘记得加上change事件里，useNormalModel只处理了update事件

2024-03-14 03:10 UTC, ocean-gao commented
1. modelValue  prop default 设置默认值为 0，否则会导致组件内部和外部变量值不统一
2. 文档文案优化，增加prop展示项 
```
modelValue / v-model     |       已激活图标个数             | number           |      0                    |
```
3. merge最新仓库代码后，拉取新分支，单独pr，否则会导致提交信息混乱
4. 命名优化：
```
   const [currentValue, updateCurrentValue] = useNormalModel(props, emit, {
        defaultValue: 0
  })

  prop已有 modelValue命名了，所以需要取另一个名字作为当前value变量名，避免混淆和歧义
```

2024-03-14 03:36 UTC, closed without merging